name: feature-pipeline
on: [push]
jobs:
  feature-pipeline:
    uses: NagineniHari/Workflows/.github/workflows/feature-nodejs-pipeline.yaml@main
    with:
      project: safety
      component: catalogue
      